version: "3.9"

services:
  backend:
    build: ./backend
    container_name: tradex-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: tradex-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:4000
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: tradex-net 